### ISSUE TITLE
How to download uncorpus

### ISSUE THREAD

**Issue by sy950921** [noe/wmt19-news-lowres#1]
Hello, I find that uncorpus website limit my download speed within 120KB/s and download time is also limited within 70min. I have tried on directly download on web and your auto download script. It doesn't work. Do you come with this problem?

**Comment by noe** [comment]
To what corpus are you referring to?

**Comment by noe** [comment]
I never encountered any of such restrictions when downloading the UN corpus. You should contact the site maintainers to consult how to address the problem.

**Comment by sy950921** [comment]
Thank you very much.
